insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),1, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),2, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),3, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),4, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),5, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),6, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),7, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),8, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),9, 5);
insert into book_rating (id,book_id,stars) values (nextval('hibernate_sequence'),10,5);